package optional;

import java.util.Optional;

public class Test {

	public static void main(String[] args) {

		// get
		Optional<String> optional = Optional.of("Hello World");
		System.out.println(optional.get()); // Outputs: Hello World

		// isPresent
		optional = Optional.ofNullable(null);
		if (optional.isPresent()) {
			System.out.println(optional.get());
		} else {
			System.out.println("No value present"); 
		}

		// ifPresent
		optional = Optional.of("Present Value");
		optional.ifPresent(
				value -> System.out.println("The value is: " + value)
			);
		// Outputs: The value is: Present Value
		
		
		// orElse example
		optional = Optional.empty();
		String orElseResult = optional.orElse("Default Value");
		System.out.println(orElseResult); // Outputs: Default Value

		// orElseGet example
		optional = Optional.empty();
		String orElseGetResult = optional.orElseGet(() -> {
			return "Generated by Supplier";
		});
		System.out.println(orElseGetResult); 
		// Outputs: Generated by Supplier

		//map
		 optional = Optional.of("Present Value");
		 Optional<Integer> optionalLength = optional.map(String::length);
		 optionalLength.ifPresent(length -> System.out.println("Length: " + length));



		// Throws IllegalStateException with the message "Value not present"
		optional = Optional.empty();
		String result = optional.orElseThrow(() -> new IllegalStateException("Value not present"));

	}

}
